# Generated by Django 3.0 on 2019-12-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='findstock',
            old_name='name',
            new_name='Interval',
        ),
        migrations.AddField(
            model_name='findstock',
            name='Symbol',
            field=models.CharField(default='hjk', max_length=200),
            preserve_default=False,
        ),
    ]
